In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
#Importing the libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
#Loading the ptbdb dats set
abnormal     = pd.read_csv("/content/drive/My Drive/Colab Notebooks/datafiles/ptbdb_abnormal.csv", header = None)
normal       = pd.read_csv("/content/drive/My Drive/Colab Notebooks/datafiles/ptbdb_normal.csv", header = None)
mitbih_test  = pd.read_csv("/content/drive/My Drive/Colab Notebooks/datafiles/mitbih_test.csv", header=None)
mitbih_train = pd.read_csv("/content/drive/My Drive/Colab Notebooks/datafiles/mitbih_train.csv", header=None)

In [4]:
abnormal.shape

(10506, 188)

In [5]:
# id_0 = np.where(abnormal[187]==0)
# id_1 = np.where(abnormal[187]==1)
# abnormal[id_0] = 5
# abnormal[id_1] = 6
# # print(abnormal)
abnormal[187].sum()

10506.0

In [6]:
abnormal[187] = 5

In [7]:
abnormal[187].unique()

array([5])

In [8]:
normal.shape

(4046, 188)

In [9]:
normal[187].sum()

0.0

In [10]:
normal[187] = 6

In [11]:
normal[187].unique()

array([6])

In [12]:
print(10506*0.25)
print(10506-2627)

2626.5
7879


In [13]:
print(4046*0.25)
print(4046-1012)

1011.5
3034


In [14]:
a = abnormal.head(2627)
a1 = abnormal.tail(7878)

In [15]:
b = normal.head(1012)
b1 = normal.tail(3034)

In [16]:
#Concatinating abnormal and normal
ptbdb_test = pd.concat([a, b])
ptbdb_train = pd.concat([a1, b1])

In [17]:
#Dimisions of the dataset
ptbdb_train.shape

(10912, 188)

In [18]:
#Diminsions of the dataset
ptbdb_test.shape

(3639, 188)

In [19]:
#Combinig the train data
train = pd.concat([mitbih_train, ptbdb_train])
train.shape

(98466, 188)

In [20]:
#Combining the test data
test = pd.concat([mitbih_test, ptbdb_test])
test.shape

(25531, 188)

In [21]:
#Finding the number of classes in the datset
train[187].unique()

array([0., 1., 2., 3., 4., 5., 6.])

In [22]:
#Feature Scaling
x_train = train.iloc[:, :-1].values
y_train = train.iloc[:, -1].values

In [23]:
#Feature Scaling
x_test = test.iloc[:, :-1].values
y_test = test.iloc[:, -1].values

In [24]:
#Dimminsion of the dataset
x_test.shape

(25531, 187)

In [25]:
#Diminsion of the dataset
y_test.shape

(25531,)

## **Random Forest Classifier**

In [26]:
#Random Forest classification
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(n_estimators = 15, criterion = 'entropy', random_state = 0)
RFC.fit(x_train, y_train)    

RandomForestClassifier(criterion='entropy', n_estimators=15, random_state=0)

In [27]:
#Predicting the test values
pred_RFC = RFC.predict(x_test)

In [28]:
#Obtaining the confusion matrix, accuracy score and classification report
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

cm_RFC = confusion_matrix(y_test, pred_RFC)
print(cm_RFC)
a_RFC = accuracy_score(y_test, pred_RFC)
print("Accuarcy of the model",a_RFC)
print(classification_report(y_test, pred_RFC))

[[18059    12     9     0     4    31     3]
 [  209   339     1     0     1     4     2]
 [  151     2  1266    14     3    12     0]
 [   52     0    12    98     0     0     0]
 [   79     0     6     0  1517     6     0]
 [  561     0    10     0     3  2033    20]
 [  165     0     0     0     0    36   811]]
Accuarcy of the model 0.944851357173632
              precision    recall  f1-score   support

         0.0       0.94      1.00      0.97     18118
         1.0       0.96      0.61      0.75       556
         2.0       0.97      0.87      0.92      1448
         3.0       0.88      0.60      0.72       162
         4.0       0.99      0.94      0.97      1608
         5.0       0.96      0.77      0.86      2627
         6.0       0.97      0.80      0.88      1012

    accuracy                           0.94     25531
   macro avg       0.95      0.80      0.86     25531
weighted avg       0.95      0.94      0.94     25531



## **KNeighbor Classification**

In [29]:
#Kneighbors classification
from sklearn.neighbors import KNeighborsClassifier
KNN = KNeighborsClassifier(n_neighbors = 15, metric = 'minkowski', p = 2)
KNN.fit(x_train, y_train)    

KNeighborsClassifier(n_neighbors=15)

In [30]:
#Predicting the test values
pred_KNN = KNN.predict(x_test)

In [31]:
#Obtainig the confusion matrix, accuracy score and classification report
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

cm_KNN = confusion_matrix(y_test, pred_KNN)
print(cm_KNN)
a_KNN = accuracy_score(y_test, pred_KNN)
print("Accuarcy of the model",a_KNN)
print(classification_report(y_test, pred_KNN))

[[17943    35    58     7     3    46    26]
 [  216   328     6     0     0     3     3]
 [  150     4  1252    23     2    11     6]
 [   48     0    13   101     0     0     0]
 [   96     0    11     0  1496     5     0]
 [  752    13    15     2     6  1744    95]
 [  380     4     0     0     0    64   564]]
Accuarcy of the model 0.9176295483921507
              precision    recall  f1-score   support

         0.0       0.92      0.99      0.95     18118
         1.0       0.85      0.59      0.70       556
         2.0       0.92      0.86      0.89      1448
         3.0       0.76      0.62      0.68       162
         4.0       0.99      0.93      0.96      1608
         5.0       0.93      0.66      0.78      2627
         6.0       0.81      0.56      0.66      1012

    accuracy                           0.92     25531
   macro avg       0.88      0.75      0.80     25531
weighted avg       0.92      0.92      0.91     25531



## **Naive Bayes**

In [32]:
#Training the Navie Bayes
from sklearn.naive_bayes import GaussianNB
NB = GaussianNB()
NB.fit(x_train, y_train)

GaussianNB()

In [33]:
#Predicting the test values
pred_NB = NB.predict(x_test)

In [34]:
#Obtainig confusion matrix, accuracy score and classification report
from sklearn.metrics import confusion_matrix, accuracy_score
from sklearn.metrics import classification_report

cm_NB = confusion_matrix(y_test, pred_NB)
print(cm_NB)
a_NB = accuracy_score(y_test, pred_NB)
print("Accuarcy of the model",a_NB)
print(classification_report(y_test, pred_NB))

[[   71    41  1062  2162 12527   208  2047]
 [    7    52    29    50   349    12    57]
 [    9     9   272    78   950    16   114]
 [    0     0     1   134    27     0     0]
 [    0     0     5     9  1592     2     0]
 [    6     9   107   134  1983    29   359]
 [    5    23    45     5   557    18   359]]
Accuarcy of the model 0.09827268810465709
              precision    recall  f1-score   support

         0.0       0.72      0.00      0.01     18118
         1.0       0.39      0.09      0.15       556
         2.0       0.18      0.19      0.18      1448
         3.0       0.05      0.83      0.10       162
         4.0       0.09      0.99      0.16      1608
         5.0       0.10      0.01      0.02      2627
         6.0       0.12      0.35      0.18      1012

    accuracy                           0.10     25531
   macro avg       0.24      0.35      0.11     25531
weighted avg       0.55      0.10      0.04     25531



## **Ensemling Classification**

In [35]:
from sklearn.ensemble import VotingClassifier

model = VotingClassifier(estimators=[('NB', NB), ('knn', KNN), ('rfc', RFC)])
model.fit(x_train, y_train)
model.score(x_test, y_test)

0.919196271199718